### PR TITLE
feat: add flag to limit preview size

### PR DESCRIPTION
**Pull request by mtvrsh**

### CODE REVIEW

**Comment by sentriz** [comment]
thanks! can you add a test please using https://github.com/rogpeppe/go-internal/testscript

**Comment by sentriz** [comment]
could we also use the name preview-width , I think that's a little nicer

**Comment by mtvrsh** [comment]
Ok, so I added `randstr` helper because I couldn't get `rand` to emit fixed width strings.
Let me know if I missed any test cases.

**Comment by sentriz** [comment]
very nice, thanks!

**Pull request merged**
