### PR TITLE
Add show command to show the content of an item id

### PR DESCRIPTION
**Pull request by chmouel**
Add the show comment to show the content of an item id. This is useful for integration with scripts.

For example with this command I can integrate image preview with fzf and [ueberzugpp](https://github.com/jstkdng/ueberzugpp).

Here is the fzf script to select and preview the clipboard:

https://gist.github.com/chmouel/723b88ac10e85510f7c9f7323d634577

and here is a quick demo on how it works

https://github.com/sentriz/cliphist/assets/98980/ca7bd5c8-c0fa-4a3a-a4f0-1bdbdb6b0b45

### CODE REVIEW

**Comment by sentriz** [comment]
it think is the same as `cliphist decode $id`

**Comment by sentriz** [comment]
as far as I can see, it is. thanks but closing for now

**Comment by chmouel** [comment]
you are right 🤦🏻 

i can contribute the fzf script or you rather i keep it externally?

**Comment by sentriz** [comment]
sure yeah feel free to stick it in contrib/

**Pull request closed without merging**
