### PR TITLE
Add support for BMP file format

### PR DESCRIPTION
**Pull request by kirizdev**

### CODE REVIEW

**Comment by sentriz** [comment]
why close? it looked good to me

**Comment by kirizdev** [comment]
Sorry, I messed up a bit 😕. Should I create another pull request?

**Comment by sentriz** [comment]
no worries, i just co-authored and pushed it with tests + `go mod tidy`

**Comment by kirizdev** [comment]
I have also written tests but forgot to commit them, lol. Thank you!

**Pull request closed without merging**
