### PR TITLE
don't store if MIME==x-kde-passwordManagerHint

### LINKED ISSUE #80: Implement secret clipboard entry conventions
https://github.com/keepassxreboot/keepassxc/issues/10233#issuecomment-1913151267

Code snippet from keepassxc
```cpp
    mime->setData("x-kde-passwordManagerHint", QByteArrayLiteral("secret"));
```

### PR DESCRIPTION
**Pull request by mjholub**
This is a very simple way to resolve #80 done by launching a subcommand and matching it's output against `x-kde-passwordManagerHint`, although I've also tried a more low-level solution using a native Go wayland library, see [mjholub/cliphist@low-level-polling](https://github.com/mjholub/cliphist/tree/low-level-polling), but I'm not really sure how to properly capture the received data.

### CODE REVIEW

**Comment by sentriz** [comment]
I think this would make more sense to live with wl-paste. eg if there was a --watch --type text!x-kde-passwordManagerHint or something

**Comment by sentriz** [comment]
or generally some way for wl-paste to not call the watched command if the there is a particular meme on offer

what do you think @bugaevc

**Comment by bugaevc** [comment]
`wl-paste` should set `CLIPBOARD_STATE=sensitive` (once https://github.com/bugaevc/wl-clipboard/pull/204 or an equivalent gets merged) in that case, but it will still run the command; it's up to you to decide to ignore it based on `CLIPBOARD_STATE` being `sensitive`.

**Comment by sentriz** [comment]
ah i see, then @mjholub we can wait until https://github.com/bugaevc/wl-clipboard/pull/204, since cliphist already supports the `sensitive` var https://github.com/sentriz/cliphist/blob/master/cliphist.go#L57

thanks @bugaevc!

**Comment by Frestein** [comment]
@sentriz  Can it be realized now?
https://github.com/bugaevc/wl-clipboard/commit/e3c1b21ddd0885fba909602cf21e9f4f35862dea
https://github.com/bugaevc/wl-clipboard/commit/1e50b65d5ef94d2e595cfaf30a81f933ba80b1f9

**Comment by sentriz** [comment]
@Frestein if your build of wl-clipboard is already setting CLIPBOARD_STATE=sensitive, it should already be working since cliphist will respect that flag

**Pull request closed without merging**
