### PR TITLE
Fix db deadlock when running multiple instances at once

### PR DESCRIPTION
**Pull request by ThinkChaos**
Hi,

I ran into #24 and the timeout fix is a bit hacky. Unfortunately I can't build the latest commit (when using vendoring), so I'm opening this PR targeting an older commit just to show you how this can be properly fixed.

Basically there's a race for locking the DB, so the solution is closing it earlier, and opening it later. More specifically, before writing to/after reading from stdout/stdin is done so the process earlier/later in the shell pipeline has exited (or at least unlocked).

I hope you can port this to the latest commit and make a new release.
Thanks!

### CODE REVIEW

**Comment by sentriz** [comment]
thanks! makes sense since every command in the pipeline starts at once

**Comment by sentriz** [comment]
how does it work for you with this? https://github.com/sentriz/cliphist/releases/tag/v0.3.1

**Comment by dogknowsnx** [comment]
It's working flawlessly here, so far.
Thanks @sentriz @ThinkChaos

**Comment by ThinkChaos** [comment]
Works for me too. Thanks for being so quick!

P.S. Figured out my issue with vendoring: was using Go 1.17 instead of 1.16

**Comment by sentriz** [comment]
nice! thanks for the patch :)

**Pull request closed without merging**
